### PR TITLE
Changes protocol from composer URL

### PR DESCRIPTION
**Pull request by nelsonsar**
Composer installation now needs to be done with HTTPS, since doing it using HTTP will return a NGINX response with status 302 like this one:
```
<html>
    <head><title>302 Found</title></head>
    <body bgcolor="white">
      <center><h1>302 Found</h1></center>
      <hr><center>nginx</center>
    </body>
</html>
```

and will not download the installer. By using ```https://getcomposer.org/installer``` the installation will occur just fine.

This fix issue #516

### CODE REVIEW

**Comment by tomtomau** [comment]
+1

**Comment by shakaran** [comment]
I just did another PR (https://github.com/everzet/capifony/pull/568) without see this

The only difference with my PR and yours is the -S param. 

Note that in https://getcomposer.org/download/ recommends use -S for show errors in curl fetching

**Comment by jiglesiasabio** [comment]
@skolodyazhnyy Proposes a workaround at https://github.com/everzet/capifony/issues/516#issuecomment-96411910

Maybe can help while this gets merged... :)

**Comment by odimodugno** [comment]
+1

**Comment by 1ed** [comment]
@willdurand could you please merge this and create a release ASAP. Thank you!

**Comment by willdurand** [comment]
duplicate of #568

**Pull request closed without merging**
