### PR TITLE
Update symfony.rb

### PR DESCRIPTION
**Pull request by szabogyula**
The getcomposer installer url is changed.

### CODE REVIEW

**Comment by ke20** [comment]
There is another pull-request for that #568

**Comment by alcaeus** [comment]
Sorry to vent on you, but does anybody check whether there already is a PR? So far we've had 
#567, #568, #569, #571 and now yours. Alright people, we got it, it's broken.

**Comment by szabogyula** [comment]
ok, sorry.

**Comment by willdurand** [comment]
see #568

**Pull request closed without merging**
