### PR TITLE
Replacing latest_release with current_path

### PR DESCRIPTION
**Pull request by bigfoot90**
Solving https://github.com/everzet/capifony/issues/551

I've written some tests also, but I'm unable to pass [test at line 41](https://github.com/bigfoot90/capifony/commit/a5f82c5e83752bd0747220f506850d08f1e357c7#diff-8eff6a4bec74f3e5588ea8e7f9a6ab84R41)

### CODE REVIEW

**Comment by bigfoot90** [comment]
@everzet ping

**Comment by willdurand** [comment]
Well, if tests don't pass, no chance to get this PR merged :/

**Comment by bigfoot90** [comment]
@willdurand I'm not a Ruby expert, I'm trying to write ruby for first time. Please give me tiny help.

How to test that 
```ruby
put result, "#{current_path}/#{web_path}/#{maintenance_basename}.html", :mode => 0644
```
is called and file has been created?

Tried for ```File.exists?``` but it checks for file on local server, not the remote one.

**Comment by bigfoot90** [comment]
@everzet @willdurand Finaly found a working solution. What now?

**Comment by willdurand** [comment]
great! squash your commits and I'll be happy to merge your PR :)

**Comment by bigfoot90** [comment]
@willdurand

**Comment by willdurand** [comment]
thanks!

**Pull request merged**
