### PR TITLE
[assets] Update_assets_version by date of last modified file

### PR DESCRIPTION
**Pull request by bigfoot90**
Solve https://github.com/everzet/capifony/issues/553 and https://github.com/everzet/capifony/issues/472
And also related with https://github.com/everzet/capifony/pull/473

### CODE REVIEW

**Comment by bigfoot90** [comment]
I've moved ```update_assets_version``` after ```composer install``` because I want to run ```assetic:dump``` beforet, herefore I need to have vendors installed.

**Comment by bigfoot90** [comment]
ping @willdurand

**Comment by willdurand** [comment]
sorry for the delay, thanks!

**Comment by bigfoot90** [comment]
@willdurand Thanks. Can you make new tag ```v2.8.4```?

**Comment by willdurand** [comment]
I will!

**Pull request merged**
