### PR TITLE
Add compatibility for the Symfony 3 directory structure

### PR DESCRIPTION
**Pull request by adamelso**
I've been using this in two new Symfony projects for a couple of months now, one of them is quite large and I haven't had any issues. However, my Ruby skills aren't the best and given this project supports Symfony 1 and Symfony 2, there should probably be a `capifony_symfony3.rb` file also.

So to use it with the new directory structure, you just configure:

```ruby
set :use_symfony_3_dirs, true
```

However in the composer.json for a new Symfony project, there are the options `symfony-var-dir` and `symfony-bin-dir`. If these are customized, then you configure these to match also.

```ruby
set :bin_path, "bin"
set :var_path, "var"
```

### CODE REVIEW

**Comment by adamelso** [comment]
It's a little demotivating to see a pull request closed without any feedback... :/

**Comment by willdurand** [comment]
oups, it should not have been closed, sorry.

**Comment by willdurand** [comment]
I have triggered the build again. Let's see if it is mergeable.

**Comment by rYsvelain** [comment]
@adamelso Could you update your tests and check again ? It's a great PR and Symfony developers already need it ;)

**Comment by adamelso** [comment]
I've decided to close this PR anyway since it doesn't address a bug fix and the solution can be easily set in the user's Capistrano/Capifony config (as I had been doing so for a while). Cheers!

**Pull request closed without merging**
