### PR TITLE
Fix the maintenance page - Fixes #578

### LINKED ISSUE #578: deploy:web:disable error since v2.8.4
Hi,

I'm using Capifony and the underlying Capistrano maintenance system to enable and disable my application and since upgrade to capifony 2.8.4 version the following error occurs:
```
/home/[...]/.rvm/gems/ruby-2.1.5/gems/capifony-2.8.4/lib/symfony2/web.rb:55:in `initialize': No such file or directory @ rb_sysopen - /home/[...]/current/web/maintenance.html (Errno::ENOENT)
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capifony-2.8.4/lib/symfony2/web.rb:55:in `new'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capifony-2.8.4/lib/symfony2/web.rb:55:in `block (3 levels) in load'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:89:in `execute_task'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `each'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:34:in `execute!'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/lib/capistrano/cli/execute.rb:14:in `execute'
        from /home/[...]/.rvm/gems/ruby-2.1.5/gems/capistrano-2.15.5/bin/cap:4:in `<top (required)>'
        from /home/[...]/.rvm/gems/ruby-2.1.5/bin/cap:23:in `load'
        from /home/[...]/.rvm/gems/ruby-2.1.5/bin/cap:23:in `<main>'
        from /home/[...]/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /home/[...]/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>
```

I downgraded capifony and found that up to 2.8.3 it's working ;)

### PR DESCRIPTION
**Pull request by WouterSioen**

### CODE REVIEW

**Comment by WouterSioen** [comment]
poke @everzet @willdurand

**Comment by WouterSioen** [comment]
poke @everzet @willdurand

**Comment by WouterSioen** [comment]
poke @everzet @willdurand

**Comment by sagikazarmark** [comment]
:+1:

**Comment by WouterSioen** [comment]
poke @everzet @willdurand

**Comment by WouterSioen** [comment]
@everzet @willdurand poke

**Comment by aur1mas** [comment]
will this PR will be merged? it's a clear bugfix.

**Comment by WouterSioen** [comment]
@everzet @willdurand poke

**Comment by WouterSioen** [comment]
I assume this will never be merged, so going to close this

**Pull request closed without merging**
